insert into t_area_muni(description) value('Tecnologia de Informacion');
insert into t_area_muni(description) value('Politica y Estrategico');
insert into t_area_muni(description) value('Fiscalizacion');
insert into t_area_muni(description) value('Asesoria y Control');
insert into t_area_muni(description) value('Direccion de Hacienda Municipal');
insert into t_area_muni(description) value('RRHH');
insert into t_area_muni(description) value('Proveeduria');
insert into t_area_muni(description) value('Servicios Generales');
insert into t_area_muni(description) value('Direccion de Servicio Publicos');
insert into t_area_muni(description) value('Direccion de Desarrollo Humano');
select * from t_area_muni;