-- MySQL Script generated by MySQL Workbench
-- Thu Sep 30 19:18:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema si_db
-- -----------------------------------------------------

-- MySQL Workbench Synchronization
-- Generated: 2021-10-04 12:50
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: dicar

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `si_db`.`SI_USERS` 
DROP FOREIGN KEY `FK_email`;

ALTER TABLE `si_db`.`SI_OFFICIALS` 
DROP FOREIGN KEY `FK_department`;

CREATE TABLE IF NOT EXISTS `si_db`.`SI_USER_ROLES` (
  `PK_USER_ROL` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_user` INT(11) NOT NULL,
  `FK_rol` INT(11) NOT NULL,
  INDEX `FK_rol_idx` (`FK_rol` ASC) VISIBLE,
  INDEX `FK_user_role_idx` (`FK_user` ASC) VISIBLE,
  PRIMARY KEY (`PK_USER_ROL`),
  UNIQUE INDEX `PK_USER_ROL_UNIQUE` (`PK_USER_ROL` ASC) VISIBLE,
  CONSTRAINT `FK_user_role`
    FOREIGN KEY (`FK_user`)
    REFERENCES `si_db`.`SI_USERS` (`PK_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_rol`
    FOREIGN KEY (`FK_rol`)
    REFERENCES `si_db`.`SI_ROLES` (`PK_ROL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `si_db`.`SI_USERS` 
DROP FOREIGN KEY `FK_official_user`;

ALTER TABLE `si_db`.`SI_USERS` ADD CONSTRAINT `FK_official_user`
  FOREIGN KEY (`FK_official`)
  REFERENCES `si_db`.`SI_OFFICIALS` (`PK_OFFICIAL`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_email`
  FOREIGN KEY (`FK_email`)
  REFERENCES `si_db`.`SI_OFFICIALS` (`email`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `si_db`.`SI_OFFICIALS` 
ADD CONSTRAINT `FK_department`
  FOREIGN KEY (`FK_department`)
  REFERENCES `si_db`.`SI_DEPARTMENTS` (`PK_DEPARTMENT`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;




USE `si_db`;
DROP procedure IF EXISTS `authenticateViaEmail`;
DELIMITER $$
USE `si_db`$$
CREATE PROCEDURE `authenticateViaEmail` (emailPrt varchar(45), passwordPrt varchar(45))
BEGIN
  SELECT PK_USER, FK_official, FK_email, password FROM si_db.SI_USERS WHERE FK_email = emailPrt AND password = SHA2(passwordPrt, 256);
END$$
DELIMITER ;



USE `si_db`;
DROP procedure IF EXISTS `authenticateViaUsername`;
DELIMITER $$
USE `si_db`$$
CREATE PROCEDURE `authenticateViaUsername` (userPrt int, passwordPrt varchar(45))
BEGIN
  SELECT PK_USER, FK_official, FK_email, password FROM si_db.SI_USERS WHERE PK_USER = userPrt AND password = SHA2(passwordPrt, 256);
END$$
DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



